/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ventanas;

import javax.swing.JPanel;

/**
 *
 * @author jdavid
 */
public class reciclaje2 extends javax.swing.JPanel {

    /**
     * Creates new form reciclaje2
     */
    public reciclaje2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        reciclaje2 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea5 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        anterior1 = new javax.swing.JButton();
        siguiente1 = new javax.swing.JButton();
        anterior = new javax.swing.JLabel();
        siguiente = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        atras = new javax.swing.JToggleButton();
        jLabel22 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(1200, 700));
        setPreferredSize(new java.awt.Dimension(1200, 700));

        reciclaje2.setMinimumSize(new java.awt.Dimension(1200, 700));
        reciclaje2.setPreferredSize(new java.awt.Dimension(1200, 700));
        reciclaje2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane5.setBackground(new java.awt.Color(215, 206, 158));
        jScrollPane5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 0));
        jScrollPane5.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane5.setHorizontalScrollBar(null);

        jTextArea5.setEditable(false);
        jTextArea5.setBackground(new java.awt.Color(221, 230, 237));
        jTextArea5.setColumns(20);
        jTextArea5.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        jTextArea5.setForeground(new java.awt.Color(204, 0, 0));
        jTextArea5.setLineWrap(true);
        jTextArea5.setRows(5);
        jTextArea5.setText(" Incluye materiales que requieren un manejo \n    especial, como pilas, baterías, productos \n químicos, aceite usado, medicinas caducadas        y aparatos electrónicos pequeños. Su \n  disposición adecuada evita daños al medio\n                    ambiente y a la salud.");
        jTextArea5.setToolTipText("");
        jTextArea5.setBorder(null);
        jScrollPane5.setViewportView(jTextArea5);

        reciclaje2.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 460, 320, 150));

        jScrollPane4.setBackground(new java.awt.Color(215, 206, 158));
        jScrollPane4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 0));
        jScrollPane4.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane4.setHorizontalScrollBar(null);

        jTextArea4.setEditable(false);
        jTextArea4.setBackground(new java.awt.Color(221, 230, 237));
        jTextArea4.setColumns(20);
        jTextArea4.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        jTextArea4.setForeground(new java.awt.Color(51, 102, 255));
        jTextArea4.setLineWrap(true);
        jTextArea4.setRows(5);
        jTextArea4.setText("       Se usa para depositar materiales como \n hojas, cuadernos, cajas de cartón, periódicos   y revistas. Es importante que estén limpios y secos, sin residuos de alimentos, para facilitar                     el proceso de reciclaje.");
        jTextArea4.setToolTipText("");
        jTextArea4.setBorder(null);
        jScrollPane4.setViewportView(jTextArea4);

        reciclaje2.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 460, 320, 150));

        jScrollPane3.setBackground(new java.awt.Color(215, 206, 158));
        jScrollPane3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 0));
        jScrollPane3.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane3.setHorizontalScrollBar(null);

        jTextArea3.setEditable(false);
        jTextArea3.setBackground(new java.awt.Color(221, 230, 237));
        jTextArea3.setColumns(20);
        jTextArea3.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        jTextArea3.setForeground(java.awt.Color.yellow);
        jTextArea3.setLineWrap(true);
        jTextArea3.setRows(5);
        jTextArea3.setText("       Aquí van envases de plástico (botellas, \n  bolsas, envoltorios), latas de aluminio, tapas           y otros metales ligeros. Antes de \n       desecharlos, enjuágalos para evitar \n      contaminación con restos orgánicos.");
        jTextArea3.setToolTipText("");
        jTextArea3.setBorder(null);
        jScrollPane3.setViewportView(jTextArea3);

        reciclaje2.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 460, 320, 140));

        anterior1.setBorderPainted(false);
        anterior1.setContentAreaFilled(false);
        anterior1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        anterior1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anterior1ActionPerformed(evt);
            }
        });
        reciclaje2.add(anterior1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 620, 30, 30));

        siguiente1.setBorderPainted(false);
        siguiente1.setContentAreaFilled(false);
        siguiente1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        siguiente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siguiente1ActionPerformed(evt);
            }
        });
        reciclaje2.add(siguiente1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 620, 30, 30));

        anterior.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        anterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/previous.png"))); // NOI18N
        anterior.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        reciclaje2.add(anterior, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 610, 50, 50));

        siguiente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        siguiente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/next.png"))); // NOI18N
        siguiente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        reciclaje2.add(siguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 610, 50, 50));

        jLabel19.setBackground(new java.awt.Color(157, 178, 191));
        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 33)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(221, 230, 237));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("¿Como Reciclar?");
        jLabel19.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel19.setOpaque(true);
        reciclaje2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 40, 340, 50));

        jLabel8.setBackground(new java.awt.Color(82, 109, 130));
        jLabel8.setOpaque(true);
        reciclaje2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 30, 360, 70));

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 0, 0));
        jLabel7.setText("Rojo (residuos peligrosos)");
        reciclaje2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 140, 220, -1));

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 102, 255));
        jLabel6.setText("Azul (papel y cartón)");
        reciclaje2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 140, 180, -1));

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jLabel5.setForeground(java.awt.Color.yellow);
        jLabel5.setText("Amarillo (plásticos y metales)");
        reciclaje2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 250, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/recycle-bin (5).png"))); // NOI18N
        reciclaje2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 190, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/recycle-bin (4).png"))); // NOI18N
        reciclaje2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 190, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/recycle-bin (3).png"))); // NOI18N
        reciclaje2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, -1, -1));

        atras.setBorderPainted(false);
        atras.setContentAreaFilled(false);
        atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasActionPerformed(evt);
            }
        });
        reciclaje2.add(atras, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 50, 40));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/back.png"))); // NOI18N
        reciclaje2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 40, 40));

        jLabel1.setBackground(new java.awt.Color(221, 230, 237));
        jLabel1.setForeground(new java.awt.Color(98, 111, 71));
        jLabel1.setOpaque(true);
        reciclaje2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 700));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(reciclaje2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(reciclaje2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ponerPanel(JPanel p) { 
    // Establecer tamaño y ubicación para el panel a agregar
        reciclaje2.removeAll();

    // Establecer tamaño y ubicación para el panel a agregar
        p.setSize(reciclaje2.getWidth(), reciclaje2.getHeight()); // Ajusta al tamaño del panelDerecha
        p.setLocation(0, 0); // Establecer la ubicación en el panelDerecha

        // Agregar el panel al contenedor sin especificar layout
        reciclaje2.add(p, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1)); // Usando AbsoluteConstraints

        // Revalidar y repaint
        reciclaje2.revalidate();
        reciclaje2.repaint();
    }
    
    private void atrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasActionPerformed
        menuPanel p = new menuPanel();
        ponerPanel(p);
    }//GEN-LAST:event_atrasActionPerformed

    private void siguiente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siguiente1ActionPerformed
        reciclaje3 p2 = new reciclaje3();
        ponerPanel(p2);
    }//GEN-LAST:event_siguiente1ActionPerformed

    private void anterior1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anterior1ActionPerformed
        reciclaje p3 = new reciclaje();
        ponerPanel(p3);
    }//GEN-LAST:event_anterior1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel anterior;
    private javax.swing.JButton anterior1;
    private javax.swing.JToggleButton atras;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JTextArea jTextArea5;
    private javax.swing.JPanel reciclaje2;
    private javax.swing.JLabel siguiente;
    private javax.swing.JButton siguiente1;
    // End of variables declaration//GEN-END:variables
}
