/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ventanas;

import javax.swing.JPanel;

/**
 *
 * @author jdavid
 */
public class reciclaje extends javax.swing.JPanel {

    /**
     * Creates new form reciclaje
     */
    public reciclaje() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        reciclaje = new javax.swing.JPanel();
        anterior = new javax.swing.JButton();
        siguiente = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea5 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        label2 = new javax.swing.JLabel();
        label = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        atras = new javax.swing.JToggleButton();
        jLabel22 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(1200, 700));

        reciclaje.setMaximumSize(new java.awt.Dimension(1200, 700));
        reciclaje.setMinimumSize(new java.awt.Dimension(1200, 700));
        reciclaje.setPreferredSize(new java.awt.Dimension(1200, 700));
        reciclaje.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        anterior.setBorderPainted(false);
        anterior.setContentAreaFilled(false);
        anterior.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        anterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anteriorActionPerformed(evt);
            }
        });
        reciclaje.add(anterior, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 620, 30, 30));

        siguiente.setBorderPainted(false);
        siguiente.setContentAreaFilled(false);
        siguiente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        siguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siguienteActionPerformed(evt);
            }
        });
        reciclaje.add(siguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 620, 30, 30));

        jScrollPane5.setBackground(new java.awt.Color(215, 206, 158));
        jScrollPane5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 0));
        jScrollPane5.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane5.setHorizontalScrollBar(null);

        jTextArea5.setEditable(false);
        jTextArea5.setBackground(new java.awt.Color(221, 230, 237));
        jTextArea5.setColumns(20);
        jTextArea5.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        jTextArea5.setForeground(new java.awt.Color(47, 147, 5));
        jTextArea5.setLineWrap(true);
        jTextArea5.setRows(5);
        jTextArea5.setText("   Diseñado para recoger botellas, frascos y \n otros objetos de vidrio. Es fundamental que \n      los vidrios estén limpios y sin tapas o\n corchos. No se deben incluir espejos, vidrios        rotos o bombillas, ya que requieren \n           procesos de reciclaje diferentes.");
        jTextArea5.setToolTipText("");
        jTextArea5.setBorder(null);
        jScrollPane5.setViewportView(jTextArea5);

        reciclaje.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 460, 310, 150));

        jScrollPane4.setBackground(new java.awt.Color(215, 206, 158));
        jScrollPane4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 0));
        jScrollPane4.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane4.setHorizontalScrollBar(null);

        jTextArea4.setEditable(false);
        jTextArea4.setBackground(new java.awt.Color(221, 230, 237));
        jTextArea4.setColumns(20);
        jTextArea4.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        jTextArea4.setForeground(new java.awt.Color(229, 149, 52));
        jTextArea4.setLineWrap(true);
        jTextArea4.setRows(5);
        jTextArea4.setText("El naranja en los basureros de reciclaje suele  estar destinado a los residuos orgánicos o \n    biodegradables, como restos de comida,\n       cáscaras de frutas y verduras, bolsas \n     compostables, y otros materiales que se\n              descomponen naturalmente.");
        jTextArea4.setToolTipText("");
        jTextArea4.setBorder(null);
        jScrollPane4.setViewportView(jTextArea4);

        reciclaje.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 460, 310, 150));

        jScrollPane3.setBackground(new java.awt.Color(215, 206, 158));
        jScrollPane3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 0));
        jScrollPane3.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane3.setHorizontalScrollBar(null);

        jTextArea3.setEditable(false);
        jTextArea3.setBackground(new java.awt.Color(221, 230, 237));
        jTextArea3.setColumns(20);
        jTextArea3.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        jTextArea3.setLineWrap(true);
        jTextArea3.setRows(5);
        jTextArea3.setText("       Destinado a todo aquello que no puede \n      reciclarse, como pañales, papel higiénico\n      usado, servilletas muy sucias o residuos \n        mezclados que no se pueden separar.");
        jTextArea3.setToolTipText("");
        jTextArea3.setBorder(null);
        jScrollPane3.setViewportView(jTextArea3);

        reciclaje.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 460, 310, 140));

        label2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/previous.png"))); // NOI18N
        label2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        reciclaje.add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 610, 50, 50));

        label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/next.png"))); // NOI18N
        label.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        reciclaje.add(label, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 610, 50, 50));

        jLabel19.setBackground(new java.awt.Color(157, 178, 191));
        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 33)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(221, 230, 237));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("¿Como Reciclar?");
        jLabel19.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel19.setOpaque(true);
        reciclaje.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 40, 340, 50));

        jLabel8.setBackground(new java.awt.Color(82, 109, 130));
        jLabel8.setOpaque(true);
        reciclaje.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 30, 360, 70));

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(47, 147, 5));
        jLabel7.setText("Verde (vidrio)");
        reciclaje.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 140, 120, -1));

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(229, 149, 52));
        jLabel6.setText("Naranja (residuos orgánicos)");
        reciclaje.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(468, 140, 240, -1));

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jLabel5.setText("Gris o negro (residuos no reciclables)");
        reciclaje.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/recycle-bin (2).png"))); // NOI18N
        reciclaje.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 190, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/recycle-bin (1).png"))); // NOI18N
        reciclaje.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 190, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/recycle-bin.png"))); // NOI18N
        reciclaje.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, -1, -1));

        atras.setBorderPainted(false);
        atras.setContentAreaFilled(false);
        atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasActionPerformed(evt);
            }
        });
        reciclaje.add(atras, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 50, 40));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/back.png"))); // NOI18N
        reciclaje.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 40, 40));

        jLabel1.setBackground(new java.awt.Color(221, 230, 237));
        jLabel1.setForeground(new java.awt.Color(98, 111, 71));
        jLabel1.setOpaque(true);
        reciclaje.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 700));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(reciclaje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(reciclaje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void atrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasActionPerformed
        menuPanel p = new menuPanel();
        ponerPanel(p);
    }//GEN-LAST:event_atrasActionPerformed

    private void siguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siguienteActionPerformed
        reciclaje2 p2 = new reciclaje2();
        ponerPanel(p2);
    }//GEN-LAST:event_siguienteActionPerformed

    private void anteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anteriorActionPerformed
        reciclaje3 p2 = new reciclaje3();
        ponerPanel(p2);
    }//GEN-LAST:event_anteriorActionPerformed

    private void ponerPanel(JPanel p) { 
    // Establecer tamaño y ubicación para el panel a agregar
        reciclaje.removeAll();

    // Establecer tamaño y ubicación para el panel a agregar
        p.setSize(reciclaje.getWidth(), reciclaje.getHeight()); // Ajusta al tamaño del panelDerecha
        p.setLocation(0, 0); // Establecer la ubicación en el panelDerecha

        // Agregar el panel al contenedor sin especificar layout
        reciclaje.add(p, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1)); // Usando AbsoluteConstraints

        // Revalidar y repaint
        reciclaje.revalidate();
        reciclaje.repaint();
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton anterior;
    private javax.swing.JToggleButton atras;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JTextArea jTextArea5;
    private javax.swing.JLabel label;
    private javax.swing.JLabel label2;
    private javax.swing.JPanel reciclaje;
    private javax.swing.JButton siguiente;
    // End of variables declaration//GEN-END:variables
}
