/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ventanas;

import javax.swing.JPanel;

/**
 *
 * @author jdavid
 */
public class reciclaje3 extends javax.swing.JPanel {

    /**
     * Creates new form reciclaje3
     */
    public reciclaje3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        reciclaje3 = new javax.swing.JPanel();
        anterior1 = new javax.swing.JButton();
        siguiente1 = new javax.swing.JButton();
        atras = new javax.swing.JToggleButton();
        jLabel20 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        anterior = new javax.swing.JLabel();
        siguiente = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(1200, 700));
        setPreferredSize(new java.awt.Dimension(1200, 700));

        reciclaje3.setMinimumSize(new java.awt.Dimension(1200, 700));
        reciclaje3.setPreferredSize(new java.awt.Dimension(1200, 700));
        reciclaje3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        anterior1.setBorderPainted(false);
        anterior1.setContentAreaFilled(false);
        anterior1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        anterior1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anterior1ActionPerformed(evt);
            }
        });
        reciclaje3.add(anterior1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 620, 30, 30));

        siguiente1.setBorderPainted(false);
        siguiente1.setContentAreaFilled(false);
        siguiente1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        siguiente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siguiente1ActionPerformed(evt);
            }
        });
        reciclaje3.add(siguiente1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 620, 30, 30));

        atras.setBorderPainted(false);
        atras.setContentAreaFilled(false);
        atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasActionPerformed(evt);
            }
        });
        reciclaje3.add(atras, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 50, 40));

        jLabel20.setBackground(new java.awt.Color(157, 178, 191));
        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(221, 230, 237));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Limpia y seca los residuos reciclables");
        jLabel20.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel20.setOpaque(true);
        reciclaje3.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 320, 500, 30));

        jLabel26.setBackground(new java.awt.Color(157, 178, 191));
        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(221, 230, 237));
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("Crea un sistema en casa");
        jLabel26.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel26.setOpaque(true);
        reciclaje3.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 530, 500, 30));

        jLabel24.setBackground(new java.awt.Color(157, 178, 191));
        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(221, 230, 237));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("Identifica los materiales reciclables y no reciclables");
        jLabel24.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel24.setOpaque(true);
        reciclaje3.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 460, 500, 30));

        jLabel25.setBackground(new java.awt.Color(157, 178, 191));
        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(221, 230, 237));
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("Reduce y reutiliza antes de reciclar");
        jLabel25.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel25.setOpaque(true);
        reciclaje3.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 390, 500, 30));

        jLabel23.setBackground(new java.awt.Color(157, 178, 191));
        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(221, 230, 237));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("Conoce los colores de los contenedores");
        jLabel23.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel23.setOpaque(true);
        reciclaje3.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 250, 500, 30));

        jLabel21.setBackground(new java.awt.Color(157, 178, 191));
        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 33)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(221, 230, 237));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("5 tips para ser mejor reciclando");
        jLabel21.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel21.setOpaque(true);
        reciclaje3.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 1030, 60));

        jLabel9.setBackground(new java.awt.Color(82, 109, 130));
        jLabel9.setOpaque(true);
        reciclaje3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 1200, 40));

        anterior.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        anterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/previous.png"))); // NOI18N
        anterior.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        reciclaje3.add(anterior, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 610, 50, 50));

        siguiente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        siguiente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/next.png"))); // NOI18N
        siguiente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        reciclaje3.add(siguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 610, 50, 50));

        jLabel19.setBackground(new java.awt.Color(157, 178, 191));
        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 33)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(221, 230, 237));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("¿Como Reciclar?");
        jLabel19.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel19.setOpaque(true);
        reciclaje3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 40, 340, 50));

        jLabel8.setBackground(new java.awt.Color(82, 109, 130));
        jLabel8.setOpaque(true);
        reciclaje3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 30, 360, 70));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/back.png"))); // NOI18N
        reciclaje3.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 40, 40));

        jLabel1.setBackground(new java.awt.Color(221, 230, 237));
        jLabel1.setForeground(new java.awt.Color(98, 111, 71));
        jLabel1.setOpaque(true);
        reciclaje3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 700));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(reciclaje3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(reciclaje3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ponerPanel(JPanel p) { 
    // Establecer tamaño y ubicación para el panel a agregar
        reciclaje3.removeAll();

    // Establecer tamaño y ubicación para el panel a agregar
        p.setSize(reciclaje3.getWidth(), reciclaje3.getHeight()); // Ajusta al tamaño del panelDerecha
        p.setLocation(0, 0); // Establecer la ubicación en el panelDerecha

        // Agregar el panel al contenedor sin especificar layout
        reciclaje3.add(p, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1)); // Usando AbsoluteConstraints

        // Revalidar y repaint
        reciclaje3.revalidate();
        reciclaje3.repaint();
    }
    
    private void anterior1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anterior1ActionPerformed
        reciclaje2 p3 = new reciclaje2();
        ponerPanel(p3);
    }//GEN-LAST:event_anterior1ActionPerformed

    private void siguiente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siguiente1ActionPerformed
        reciclaje p1 = new reciclaje();
        ponerPanel(p1);
    }//GEN-LAST:event_siguiente1ActionPerformed

    private void atrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasActionPerformed
        menuPanel p = new menuPanel();
        ponerPanel(p);
    }//GEN-LAST:event_atrasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel anterior;
    private javax.swing.JButton anterior1;
    private javax.swing.JToggleButton atras;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel reciclaje3;
    private javax.swing.JLabel siguiente;
    private javax.swing.JButton siguiente1;
    // End of variables declaration//GEN-END:variables
}
